CREATE TABLE Users(
    u_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    u_name VARCHAR(50) NOT NULL UNIQUE,
    u_pass TEXT NOT NULL -- hashed
);

CREATE TABLE Bookmarks(
    bm_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    u_id INT NOT NULL,
    bm_link TEXT NOT NULL,
    bm_name TEXT NOT NULL,
    FOREIGN KEY (u_id) REFERENCES Users(u_id) ON DELETE CASCADE
);
